/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcssuprimentosmaven.view;

import java.awt.Cursor;
import java.awt.Dimension;
import jcssuprimentosmaven.domain.Jogador;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaArmazemDistribuicao;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaArmazemFabrica;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaArmazemSuprimento;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaDistribuidor;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaEstoqueDistribuicao;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaFabrica;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaMateriaPrima;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaPedido;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaSolicitacao;
import jcssuprimentosmaven.ouvinte.OuvinteViewPesquisaTransporte;

/**
 *
 * @author Gustavo
 */
public class ViewFluxo extends javax.swing.JInternalFrame {

    private ViewPesquisaMateriaPrima viewPesquisaMateriaPrima;
    private ViewPesquisaMeioTransporte viewPesquisaMeioTransporte;
    private ViewPesquisaFabrica viewPesquisaFabrica;
    private ViewPesquisaEmpresa viewPesquisaEmpresa;
    private ViewPesquisaArmazemSuprimento viewPesquisaArmazemSuprimento;
    private ViewPesquisaArmazemFabrica viewPesquisaArmazemFabrica;
    private ViewPesquisaArmazemDistribuicao viewPesquisaArmazemDistribuicao;
    private ViewPesquisaDistribuidor viewPesquisaDistribuidor;
    private ViewPesquisaPedido viewPesquisaPedido;
    private ViewPesquisaSolicitacao viewPesquisaSolicitacao;
    private ViewPesquisaEstoqueSuprimento viewPesquisaEstoqueSuprimento;
    private ViewPesquisaEstoqueDistribuicao viewPesquisaEstoqueDistribuicao;
    private ViewPesquisaTransporte viewPesquisaTransporte;
    private Jogador jogador;

    /**
     * Creates new form ViewFluxo
     */
    public ViewFluxo()  {
        initComponents();
        
        lPlanoFundo.setIcon(new javax.swing.ImageIcon(".\\imagem\\PainelCentral2.1.png"));

    }
    
    public ViewFluxo(Jogador jogador) {
        initComponents();
        lPlanoFundo.setIcon(new javax.swing.ImageIcon(".\\imagem\\PainelCentral2.1.png"));
        this.jogador = jogador;
        //muda o curso para a mão quando passa o mouse sobre as labels.
        lFornecedorSuprimento.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lTransporteDistribuicaoDistruidor.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lArmazemSuprimento.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lFabrica.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lDistribuidor.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lTransporteSuprimentoFabrica.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lArmazemDistribuicao.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lTransporteSuprimento.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lTransporteDistribuicao.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lArmazemFabrica.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lPlanoFundo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public Jogador getJogador() {
        if(jogador == null){
            jogador = new Jogador();
        }
        return jogador;
    }

    public void setJogador(Jogador jogador) {
        this.jogador = jogador;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lFornecedorSuprimento = new javax.swing.JLabel();
        lArmazemSuprimento = new javax.swing.JLabel();
        lDistribuidor = new javax.swing.JLabel();
        lFabrica = new javax.swing.JLabel();
        lTransporteDistribuicaoDistruidor = new javax.swing.JLabel();
        lTransporteSuprimentoFabrica = new javax.swing.JLabel();
        lArmazemDistribuicao = new javax.swing.JLabel();
        lTransporteSuprimento = new javax.swing.JLabel();
        lTransporteDistribuicao = new javax.swing.JLabel();
        lPlanoFundo = new javax.swing.JLabel();
        lArmazemFabrica = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setTitle("Fluxo de Dados");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lFornecedorSuprimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lFornecedorSuprimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFornecedorSuprimentoMouseClicked(evt);
            }
        });
        getContentPane().add(lFornecedorSuprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, 130));

        lArmazemSuprimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lArmazemSuprimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lArmazemSuprimentoMouseClicked(evt);
            }
        });
        getContentPane().add(lArmazemSuprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, 150));

        lDistribuidor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lDistribuidor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lDistribuidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lDistribuidorMouseClicked(evt);
            }
        });
        getContentPane().add(lDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 160, 160));

        lFabrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lFabrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFabricaMouseClicked(evt);
            }
        });
        getContentPane().add(lFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 150));

        lTransporteDistribuicaoDistruidor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTransporteDistribuicaoDistruidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTransporteDistribuicaoDistruidorMouseClicked(evt);
            }
        });
        getContentPane().add(lTransporteDistribuicaoDistruidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 150, 140));

        lTransporteSuprimentoFabrica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTransporteSuprimentoFabrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTransporteSuprimentoFabricaMouseClicked(evt);
            }
        });
        getContentPane().add(lTransporteSuprimentoFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 150));

        lArmazemDistribuicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lArmazemDistribuicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lArmazemDistribuicaoMouseClicked(evt);
            }
        });
        getContentPane().add(lArmazemDistribuicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 140, 150));

        lTransporteSuprimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTransporteSuprimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTransporteSuprimentoMouseClicked(evt);
            }
        });
        getContentPane().add(lTransporteSuprimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 150, 140));

        lTransporteDistribuicao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lTransporteDistribuicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTransporteDistribuicaoMouseClicked(evt);
            }
        });
        getContentPane().add(lTransporteDistribuicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 140, 150));
        getContentPane().add(lPlanoFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 610));

        lArmazemFabrica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lArmazemFabricaMouseClicked(evt);
            }
        });
        getContentPane().add(lArmazemFabrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 140, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lFornecedorSuprimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFornecedorSuprimentoMouseClicked
        // TODO add your handling code here:        
        viewPesquisaMateriaPrima = new ViewPesquisaMateriaPrima(this.jogador);
        OuvinteViewPesquisaMateriaPrima ouvinte = new OuvinteViewPesquisaMateriaPrima(viewPesquisaMateriaPrima,this.jogador);
        this.getParent().add(viewPesquisaMateriaPrima);
        viewPesquisaMateriaPrima.setVisible(true);
        viewPesquisaMateriaPrima.setPosicao();
    }//GEN-LAST:event_lFornecedorSuprimentoMouseClicked

    private void lTransporteDistribuicaoDistruidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTransporteDistribuicaoDistruidorMouseClicked
        // TODO add your handling code here:
        /*viewPesquisaMeioTransporte = new ViewPesquisaMeioTransporte(this.jogador);
        if(this.jogador.getFuncao() == 1){
            viewPesquisaMeioTransporte.bPesquisaTodos.setVisible(false);
        }
        viewPesquisaMeioTransporte.setDestino("Distribuidor(Empresa)");
        OuvinteViewPesquisaMeioTransporte ouvinte = new OuvinteViewPesquisaMeioTransporte(viewPesquisaMeioTransporte);
        this.getParent().add(viewPesquisaMeioTransporte);
        viewPesquisaMeioTransporte.setVisible(true);
        viewPesquisaMeioTransporte.setPosicao();*/
        viewPesquisaEstoqueDistribuicao = new ViewPesquisaEstoqueDistribuicao(this.jogador);
        OuvinteViewPesquisaEstoqueDistribuicao ouvinte = new OuvinteViewPesquisaEstoqueDistribuicao(viewPesquisaEstoqueDistribuicao, this.jogador);
        this.getParent().add(viewPesquisaEstoqueDistribuicao);
        viewPesquisaEstoqueDistribuicao.setVisible(true);
        viewPesquisaEstoqueDistribuicao.setPosicao();
    }//GEN-LAST:event_lTransporteDistribuicaoDistruidorMouseClicked

    private void lArmazemSuprimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lArmazemSuprimentoMouseClicked
        // TODO add your handling code here:
        viewPesquisaArmazemSuprimento = new ViewPesquisaArmazemSuprimento(this.jogador);
        OuvinteViewPesquisaArmazemSuprimento ouvinte = new OuvinteViewPesquisaArmazemSuprimento(viewPesquisaArmazemSuprimento,this.jogador);
        this.getParent().add(viewPesquisaArmazemSuprimento);
        viewPesquisaArmazemSuprimento.setVisible(true);
        viewPesquisaArmazemSuprimento.setPosicao();
    }//GEN-LAST:event_lArmazemSuprimentoMouseClicked

    private void lFabricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFabricaMouseClicked
        // TODO add your handling code here:
        viewPesquisaFabrica = new ViewPesquisaFabrica(this.jogador);
        OuvinteViewPesquisaFabrica ouvinte = new OuvinteViewPesquisaFabrica(viewPesquisaFabrica,this.jogador);
        this.getParent().add(viewPesquisaFabrica);
        viewPesquisaFabrica.setVisible(true);
        viewPesquisaFabrica.setPosicao();
    }//GEN-LAST:event_lFabricaMouseClicked

    private void lDistribuidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lDistribuidorMouseClicked
        viewPesquisaDistribuidor = new ViewPesquisaDistribuidor(this.jogador);
        OuvinteViewPesquisaDistribuidor ouvinte = new OuvinteViewPesquisaDistribuidor(viewPesquisaDistribuidor,this.jogador);
        this.getParent().add(viewPesquisaDistribuidor);
        viewPesquisaDistribuidor.setVisible(true);
        viewPesquisaDistribuidor.setPosicao();
    }//GEN-LAST:event_lDistribuidorMouseClicked

    private void lTransporteSuprimentoFabricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTransporteSuprimentoFabricaMouseClicked
        /*viewPesquisaMeioTransporte = new ViewPesquisaMeioTransporte(this.jogador);
        if(this.jogador.getFuncao() == 1){
            viewPesquisaMeioTransporte.bPesquisaTodos.setVisible(false);
        }
        viewPesquisaMeioTransporte.setDestino("Fábrica");
        OuvinteViewPesquisaMeioTransporte ouvinte = new OuvinteViewPesquisaMeioTransporte(viewPesquisaMeioTransporte);
        this.getParent().add(viewPesquisaMeioTransporte);        
        viewPesquisaMeioTransporte.setVisible(true);
        viewPesquisaMeioTransporte.setPosicao();
        
        viewPesquisaEstoqueSuprimento = new ViewPesquisaEstoqueSuprimento();
        OuvinteViewPesquisaEstoqueSuprimento ouvinte = new OuvinteViewPesquisaEstoqueSuprimento(viewPesquisaEstoqueSuprimento,this.jogador);
        this.getParent().add(viewPesquisaEstoqueSuprimento);
        viewPesquisaEstoqueSuprimento.setVisible(true);
        viewPesquisaEstoqueSuprimento.setPosicao();*/
        viewPesquisaTransporte = new ViewPesquisaTransporte(this.jogador);
        OuvinteViewPesquisaTransporte ouvinte = new OuvinteViewPesquisaTransporte(viewPesquisaTransporte, this.jogador);
        this.getParent().add(viewPesquisaTransporte);
        viewPesquisaTransporte.setVisible(true);
        viewPesquisaTransporte.setPosicao();
    }//GEN-LAST:event_lTransporteSuprimentoFabricaMouseClicked

    private void lArmazemDistribuicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lArmazemDistribuicaoMouseClicked
        viewPesquisaArmazemDistribuicao = new ViewPesquisaArmazemDistribuicao(this.jogador);
        OuvinteViewPesquisaArmazemDistribuicao ouvinte = new OuvinteViewPesquisaArmazemDistribuicao(viewPesquisaArmazemDistribuicao,this.jogador);
        this.getParent().add(viewPesquisaArmazemDistribuicao);
        viewPesquisaArmazemDistribuicao.setVisible(true);
        viewPesquisaArmazemDistribuicao.setPosicao();
    }//GEN-LAST:event_lArmazemDistribuicaoMouseClicked

    private void lTransporteSuprimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTransporteSuprimentoMouseClicked
        /*viewPesquisaMeioTransporte = new ViewPesquisaMeioTransporte(this.jogador);
        if(this.jogador.getFuncao() == 1){
            viewPesquisaMeioTransporte.bPesquisaTodos.setVisible(false);
        }
        viewPesquisaMeioTransporte.setDestino("Armazém Suprimento");
        OuvinteViewPesquisaMeioTransporte ouvinte = new OuvinteViewPesquisaMeioTransporte(viewPesquisaMeioTransporte);
        this.getParent().add(viewPesquisaMeioTransporte);
        viewPesquisaMeioTransporte.setVisible(true);
        viewPesquisaMeioTransporte.setPosicao();*/
        viewPesquisaPedido = new ViewPesquisaPedido(this.jogador);
        OuvinteViewPesquisaPedido ouvinte = new OuvinteViewPesquisaPedido(viewPesquisaPedido, this.jogador);
        this.getParent().add(viewPesquisaPedido);
        viewPesquisaPedido.setVisible(true);
        viewPesquisaPedido.setPosicao();
    }//GEN-LAST:event_lTransporteSuprimentoMouseClicked

    private void lTransporteDistribuicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTransporteDistribuicaoMouseClicked
        /*viewPesquisaMeioTransporte = new ViewPesquisaMeioTransporte(this.jogador);
        if(this.jogador.getFuncao() == 1){
            viewPesquisaMeioTransporte.bPesquisaTodos.setVisible(false);
        }
        viewPesquisaMeioTransporte.setDestino("Armazém Distribuição");
        OuvinteViewPesquisaMeioTransporte ouvinte = new OuvinteViewPesquisaMeioTransporte(viewPesquisaMeioTransporte);
        this.getParent().add(viewPesquisaMeioTransporte);
        viewPesquisaMeioTransporte.setVisible(true);
        viewPesquisaMeioTransporte.setPosicao();*/
        viewPesquisaSolicitacao = new ViewPesquisaSolicitacao(this.jogador);
        OuvinteViewPesquisaSolicitacao ouvinte = new OuvinteViewPesquisaSolicitacao(viewPesquisaSolicitacao, this.jogador);
        this.getParent().add(viewPesquisaSolicitacao);
        viewPesquisaSolicitacao.setVisible(true);
        viewPesquisaSolicitacao.setPosicao();
    }//GEN-LAST:event_lTransporteDistribuicaoMouseClicked

    private void lArmazemFabricaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lArmazemFabricaMouseClicked
        viewPesquisaArmazemFabrica = new ViewPesquisaArmazemFabrica(this.jogador);
        OuvinteViewPesquisaArmazemFabrica ouvinte = new OuvinteViewPesquisaArmazemFabrica(viewPesquisaArmazemFabrica,this.jogador);
        this.getParent().add(viewPesquisaArmazemFabrica);
        viewPesquisaArmazemFabrica.setVisible(true);
        viewPesquisaArmazemFabrica.setPosicao();
    }//GEN-LAST:event_lArmazemFabricaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lArmazemDistribuicao;
    private javax.swing.JLabel lArmazemFabrica;
    private javax.swing.JLabel lArmazemSuprimento;
    private javax.swing.JLabel lDistribuidor;
    private javax.swing.JLabel lFabrica;
    private javax.swing.JLabel lFornecedorSuprimento;
    private javax.swing.JLabel lPlanoFundo;
    private javax.swing.JLabel lTransporteDistribuicao;
    private javax.swing.JLabel lTransporteDistribuicaoDistruidor;
    private javax.swing.JLabel lTransporteSuprimento;
    private javax.swing.JLabel lTransporteSuprimentoFabrica;
    // End of variables declaration//GEN-END:variables
}
