/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcssuprimentosmaven.view;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import jcssuprimentosmaven.controller.JogadorController;
import jcssuprimentosmaven.domain.Jogador;
import jcssuprimentosmaven.util.ViewUtil;

/**
 * @author Jefferson Lucena Criação: 21/10/2016 Última modificação: 24/10/2016
 * Modificado por: Gustavo Dais
 */
public class ViewLogin extends javax.swing.JFrame {

    private Jogador jogador;
    private ViewPrincipal viewPrincipal;

    /**
     * Creates new form TelaLogin
     */
    public ViewLogin() {
        initComponents();
        //        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(".//imagem//icon_login.png"))); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(".\\imagem\\icon_login.png")); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        bAcessar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        txUsuario = new javax.swing.JTextField();
        txSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lLogoLogin = new javax.swing.JLabel();
        cbFuncao = new javax.swing.JComboBox();
        lFuncao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
<<<<<<< HEAD
        usuario.setText("Equipe:");
=======
        usuario.setText("Usuário:");
>>>>>>> 422d0a7184ad0fae75859fb8671f48ecf0ffb1a9

        senha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senha.setText("Senha:");

        bAcessar.setText("Acessar");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        lLogoLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lLogoLogin.setText("LOGIN ");

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Participante", "Juiz" }));
        cbFuncao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbFuncaoKeyPressed(evt);
            }
        });

        lFuncao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lFuncao.setText("Função");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bAcessar)
                                .addGap(79, 79, 79)
                                .addComponent(cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario)
                            .addComponent(senha)
                            .addComponent(lFuncao))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txSenha)
                            .addComponent(txUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lLogoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario)
                    .addComponent(txUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senha)
                    .addComponent(txSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFuncao))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(bAcessar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelarActionPerformed

    private void cbFuncaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbFuncaoKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER)) {

            Jogador jogador = this.preencherUsuario();
            JogadorController jogadorController = new JogadorController();
            jogadorController.setJogadorCadastro(jogador);
            Jogador autentico = jogadorController.autenticarUsuario();
            if (autentico != null) {
                this.iniciaSistema(true, autentico);
            } else {
                this.iniciaSistema(false, null);
            }

        }
    }//GEN-LAST:event_cbFuncaoKeyPressed

    public void bAcessarAddActionListener(ActionListener ouvinte) {
        bAcessar.addActionListener(ouvinte);
    }

    /*public void cbAccessarActionListener(ActionListener ouvinte){
        cbFuncao.addActionListener(ouvinte);
    }*/
    public Jogador preencherUsuario() {
        jogador = new Jogador();
        jogador.setLogin(this.txUsuario.getText());
        jogador.setSenha(this.txSenha.getText());
        String funcao = (String) this.cbFuncao.getSelectedItem();
        int funcaoAnalisar = 0;
        if (funcao.equals("Participante")) {
            funcaoAnalisar = 1;
        }
        if (funcao.equals("Juiz")) {
            funcaoAnalisar = 2;
        }
        jogador.setFuncao(funcaoAnalisar);

        return jogador;
    }

    public void iniciaSistema(boolean inicio, Jogador usuario) {
        if (inicio) {
            this.dispose();
            viewPrincipal = new ViewPrincipal(usuario);
            viewPrincipal.setVisible(true);
            viewPrincipal.setJogador(usuario);

        } else {
            ViewUtil.addMsgErro("Login/senha incorretos!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAcessar;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox cbFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lFuncao;
    private javax.swing.JLabel lLogoLogin;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField txSenha;
    private javax.swing.JTextField txUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
