/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jcssuprimentosmaven.view;

import datechooser.beans.DateChooserPanel;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import jcssuprimentosmaven.domain.Rodada;
import jcssuprimentosmaven.util.ViewUtil;
import java.util.Date;

/**
 *
 * @author Gustavo
 */
public class ViewDadosRodada extends javax.swing.JInternalFrame {

    private Rodada rodada;
    private boolean error;
    private String acao;

    /**
     * Creates new form ViewDadosRodada
     */
    public ViewDadosRodada() {
        initComponents();
        Calendar cal = new GregorianCalendar();

    }

    public boolean isError() {
        return error;
    }

    public void setError(boolean error) {
        this.error = error;
    }

    public String getAcao() {
        return acao;
    }

    public void setAcao(String acao) {
        this.acao = acao;
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public int pedirConfirmacao(String mensagem, String titulo, int tipo) {
        int resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, tipo);
        return resposta;
    }

    public void limaparCampos() {
        this.txDemanda.setText(null);
        this.txCFerroviaria.setText(null);
        this.txCRodoviaria.setText(null);
    }

    public Rodada preencherRodada() {
        rodada.setDemanda(txDemanda.getText());
        int rodoviaria = Integer.parseInt(txCRodoviaria.getText());
        rodada.setCargaRodoviaria(rodoviaria);
        int ferroviaria = Integer.parseInt(txCFerroviaria.getText());
        rodada.setCargaFerroviaria(ferroviaria);
        rodada.setDataInicio(dataInicio.getCurrent().getTime());
        rodada.setDataFim(dataFim.getCurrent().getTime());

        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        Set<ConstraintViolation<Rodada>> constraintViolation = validator.validate(rodada);

        if (!constraintViolation.isEmpty()) {
            String mensagem = "";
            for (ConstraintViolation<Rodada> erro : constraintViolation) {
                mensagem += erro.getMessage() + "\n";
                ViewUtil.addMsgErro(mensagem);
            }
            this.error = true;
        }

        return rodada;
    }

    public void exibirRodada(Rodada rodada) {
        this.limaparCampos();
        txDemanda.setText(rodada.getDemanda());
        String ferroviaria = Integer.toString(rodada.getCargaFerroviaria());
        txCFerroviaria.setText(ferroviaria);
        String rodoviaria = Integer.toString(rodada.getCargaRodoviaria());
        txCRodoviaria.setText(rodoviaria);
       if (rodada.getDataInicio()== null){
            dataInicio = new DateChooserPanel();
        }else{
           dataInicio.setSelectedDate(toCalendar(rodada.getDataInicio()));
       }
        if(rodada.getDataFim() == null){
            dataFim = new DateChooserPanel();                    
        }else{
           dataFim.setSelectedDate(toCalendar(rodada.getDataFim())); 
        }
    }

    public Calendar toCalendar(Date date) {
        Calendar data = Calendar.getInstance();
        data.setTime(date);       

        return data;
    }

    public void bGravarRodadaActionListener(ActionListener ouvinte) {
        bGravar.addActionListener(ouvinte);
    }

    public void bEditarRodadaActionListener(ActionListener ouvinte) {
        bEditar.addActionListener(ouvinte);
    }

    public void bExcluirRodadaActionListener(ActionListener ouvinte) {
        bExcluir.addActionListener(ouvinte);
    }
    
    public void bExecutarRodadaActionListener(ActionListener ouvinte){
        bExecutar.addActionListener(ouvinte);
    }

    public Rodada getRodada() {
        return rodada;
    }

    public void setRodada(Rodada rodada) {
        this.rodada = rodada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pRodada = new javax.swing.JPanel();
        ldataFim = new javax.swing.JLabel();
        lDemanda = new javax.swing.JLabel();
        lCRodoviaria = new javax.swing.JLabel();
        lCFerroviaria = new javax.swing.JLabel();
        txDemanda = new javax.swing.JTextField();
        txCRodoviaria = new javax.swing.JTextField();
        txCFerroviaria = new javax.swing.JTextField();
        bNovo = new javax.swing.JButton();
        bGravar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        ldataInicio = new javax.swing.JLabel();
        dataInicio = new datechooser.beans.DateChooserPanel();
        dataFim = new datechooser.beans.DateChooserPanel();
        bExecutar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastro - Rodada");

        pRodada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Rodada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        ldataFim.setText("Data Fim");

        lDemanda.setText("Demanda");

        lCRodoviaria.setText("Carga Rodoviária");

        lCFerroviaria.setText("Carga Ferroviária");

        bNovo.setText("Novo");
        bNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoActionPerformed(evt);
            }
        });

        bGravar.setText("Gravar");

        bEditar.setText("Editar");

        bExcluir.setText("Excluir");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        ldataInicio.setText("Data Início");

        bExecutar.setText("Executar");

        javax.swing.GroupLayout pRodadaLayout = new javax.swing.GroupLayout(pRodada);
        pRodada.setLayout(pRodadaLayout);
        pRodadaLayout.setHorizontalGroup(
            pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRodadaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCRodoviaria)
                    .addComponent(lCFerroviaria)
                    .addComponent(lDemanda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txCRodoviaria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(txDemanda, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txCFerroviaria, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(42, 42, 42)
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pRodadaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(ldataInicio))
                    .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRodadaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ldataFim))
                    .addGroup(pRodadaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(268, 268, 268))
            .addGroup(pRodadaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bNovo)
                .addGap(18, 18, 18)
                .addComponent(bGravar)
                .addGap(18, 18, 18)
                .addComponent(bEditar)
                .addGap(18, 18, 18)
                .addComponent(bExcluir)
                .addGap(18, 18, 18)
                .addComponent(bCancelar)
                .addGap(18, 18, 18)
                .addComponent(bExecutar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pRodadaLayout.setVerticalGroup(
            pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRodadaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pRodadaLayout.createSequentialGroup()
                        .addComponent(ldataFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataFim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ldataInicio)
                    .addGroup(pRodadaLayout.createSequentialGroup()
                        .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lDemanda)
                            .addComponent(txDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCRodoviaria)
                            .addComponent(txCRodoviaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCFerroviaria)
                            .addComponent(txCFerroviaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pRodadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNovo)
                    .addComponent(bGravar)
                    .addComponent(bEditar)
                    .addComponent(bExcluir)
                    .addComponent(bCancelar)
                    .addComponent(bExecutar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pRodada, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pRodada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoActionPerformed
        // TODO add your handling code here:
        this.limaparCampos();
        rodada = new Rodada();
    }//GEN-LAST:event_bNovoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bCancelar;
    protected javax.swing.JButton bEditar;
    protected javax.swing.JButton bExcluir;
    private javax.swing.JButton bExecutar;
    protected javax.swing.JButton bGravar;
    protected javax.swing.JButton bNovo;
    private datechooser.beans.DateChooserPanel dataFim;
    private datechooser.beans.DateChooserPanel dataInicio;
    private javax.swing.JLabel lCFerroviaria;
    private javax.swing.JLabel lCRodoviaria;
    private javax.swing.JLabel lDemanda;
    private javax.swing.JLabel ldataFim;
    private javax.swing.JLabel ldataInicio;
    protected javax.swing.JPanel pRodada;
    private javax.swing.JTextField txCFerroviaria;
    private javax.swing.JTextField txCRodoviaria;
    private javax.swing.JTextField txDemanda;
    // End of variables declaration//GEN-END:variables
}
